name: release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        registry:
          [
            {
              enabled: true,
              public: false,
              url: "https://npm.pkg.github.com",
              token: GITHUB_TOKEN,
            },
            { enabled: false, public: true, url: "https://registry.npmjs.org", token: NPM_TOKEN },
          ]
      fail-fast: false
    steps:
      - name: Early exit
        if: matrix.registry.enabled == false
        run: exit 0
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          registry-url: ${{ matrix.registry.url }}
          scope: "@let-value"
      - run: npm ci
      - run: npm run build
      - name: Resolve publish tag
        id: publish_tag
        run: |
          VERSION="$(npm pkg get version)"
          if [[ "$VERSION" == *-* ]]; then
            TAG="next"
          else
            TAG="latest"
          fi

          npm publish --tag "$TAG" --access ${{ matrix.registry.public && 'public' || 'restricted' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
